splits:
  - prefix: "admin"
    target: "https://${GH_TOKEN}@github.com/Mailu/Admin.git"
  - prefix: "clamav"
    target: "https://${GH_TOKEN}@github.com/Mailu/ClamAV.git"
  - prefix: "dovecot"
    target: "https://${GH_TOKEN}@github.com/Mailu/Dovecot.git"
  - prefix: "fetchmail"
    target: "https://${GH_TOKEN}@github.com/Mailu/Fetchmail.git"
  - prefix: "nginx-no-https"
    target: "https://${GH_TOKEN}@github.com/Mailu/NGINX-no-HTTPS.git"
  - prefix: "nginx"
    target: "https://${GH_TOKEN}@github.com/Mailu/NGINX.git"
  - prefix: "postfix"
    target: "https://${GH_TOKEN}@github.com/Mailu/Postfix.git"
  - prefix: "radicale"
    target: "https://${GH_TOKEN}@github.com/Mailu/Radicale.git"
  - prefix: "rainloop"
    target: "https://${GH_TOKEN}@github.com/Mailu/RainLoop.git"
  - prefix: "rmilter"
    target: "https://${GH_TOKEN}@github.com/Mailu/Rmilter.git"
  - prefix: "roundcube"
    target: "https://${GH_TOKEN}@github.com/Mailu/Roundcube.git"
  - prefix: "rspamd"
    target: "https://${GH_TOKEN}@github.com/Mailu/Rspamd.git"

origins:
  - ^master$
  - ^stable$
  - ^\d+\.\d+$
