sudo: required
services: docker
addons:
  apt:
    packages:
      - docker-ce
env:
  - VERSION=$TRAVIS_BRANCH
language: python
python:
  - "3.6"
install:
  - pip install -r tests/requirements.txt

script:
  # Default to mailu for DOCKER_ORG
  - if [ -z "$DOCKER_ORG" ]; then export DOCKER_ORG="mailu"; fi
  - docker-compose -f tests/build.yml build
  - python tests/compose/test.py

deploy:
  provider: script
  script: bash tests/deploy.sh
  on:
    all_branches: true
    condition: -n $DOCKER_UN

