sudo: required
services: docker
addons:
  apt:
    packages:
      - docker-ce
env:
  - VERSION=$TRAVIS_BRANCH

script:
  - docker-compose -f tests/build.yml -p Mailu build
  - tests/compose/test-script.sh

deploy:
  provider: script
  script: bash tests/deploy.sh
  on:
    all_branches: true
    condition: -z $DOCKER_UN

