sudo: required
services: docker
addons:
  apt:
    packages:
      - docker-ce
env:
  - MAILU_VERSION=$TRAVIS_BRANCH
language: python
python:
  - "3.6"
install:
  - pip install -r tests/requirements.txt

script:
  - docker-compose -f tests/build.yml build
# test.py, test name and timeout between start and tests.
  - python tests/compose/test.py core 1

deploy:
  provider: script
  script: bash tests/deploy.sh
  on:
    all_branches: true
    condition: -n $DOCKER_UN

