http:
  build: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - admin
    - webmail
  volumes:
    - /tmp/data/certs:/certs

imap:
  build: dovecot
  ports:
    - "143:143"
    - "993:993"
  volumes:
    - /tmp/data/freeposte:/data
    - /tmp/data/mail:/mail
    - /tmp/data/certs:/certs

smtp:
  build: postfix
  ports:
    - "25:25"
    - "465:465"
    - "587:587"
  links:
    - imap
  volumes:
    - /tmp/data/freeposte:/data
    - /tmp/data/logs:/logs
    - /tmp/data/certs:/certs

admin:
  build: admin
  volumes:
    - /tmp/data/freeposte:/data
  environment:
    - DEBUG=True
    - SECRET_KEY=mysecretkey

webmail:
  build: roundcube
  links:
    - imap
  volumes:
    - /tmp/data/webmail:/data
