version: '2'

services:

  http:
    build: nginx
    image: freeposte/reverse-proxy
    env_file: freeposte.env
    ports:
      - "80:80"
      - "443:443"
    links:
      - webmail
      - admin
    volumes:
      - /data/certs:/certs
      
  redis:
    image: redis
    volumes:
      - /data/redis:/data

  imap:
    build: dovecot
    image: freeposte/dovecot
    env_file: freeposte.env
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - /data/freeposte:/data
      - /data/mail:/mail
      - /data/certs:/certs

  smtp:
    build: postfix
    image: freeposte/postfix
    env_file: freeposte.env
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - /data/freeposte:/data
      - /data/certs:/certs

  milter:
    build: rmilter
    image: freeposte/rmilter
    env_file: freeposte.env
    volumes:
      - /data/filter:/data
      
  antispam:
    build: rspamd
    image: freeposte/rspamd
    env_file: freeposte.env
    volumes:
      - /data/filter:/var/lib/rspamd
      
  antivirus:
    build: clamav
    image: freeposte/clamav
    env_file: freeposte.env
    volumes:
      - /data/filter:/data

  admin:
    build: admin
    image: freeposte/admin
    env_file: freeposte.env
    volumes:
      - /data/freeposte:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  webmail:
    build: roundcube
    image: freeposte/roundcube
    env_file: freeposte.env
    volumes:
      - /data/webmail:/data

  fetchmail:
    build: fetchmail
    image: freeposte/fetchmail
    env_file: freeposte.env
    volumes:
      - /data/freeposte:/data
