version: '2'

services:

  http:
    build: nginx
    image: freeposte/reverse-proxy
    env_file: freeposte.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/certs:/certs

  imap:
    build: dovecot
    image: freeposte/dovecot
    env_file: freeposte.env
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - /data/freeposte:/data
      - /data/mail:/mail
      - /data/certs:/certs

  smtp:
    build: postfix
    image: freeposte/postfix
    env_file: freeposte.env
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - /data/freeposte:/data
      - /data/logs:/logs
      - /data/certs:/certs

  filter:
    build: amavis
    image: freeposte/amavis
    env_file: freeposte.env
    volumes:
      - /data/filter:/data

  admin:
    build: admin
    image: freeposte/admin
    env_file: freeposte.env
    volumes:
      - /data/freeposte:/data

  webmail:
    build: roundcube
    image: freeposte/roundcube
    env_file: freeposte.env
    volumes:
      - /data/webmail:/data
