http:
  build: nginx
  env_file: freeposte.env
  ports:
    - "80:80"
    - "443:443"
  links:
    - admin:admin
    - webmail:webmail
  volumes:
    - /tmp/data/certs:/certs

imap:
  build: dovecot
  env_file: freeposte.env
  ports:
    - "143:143"
    - "993:993"
  volumes:
    - /tmp/data/freeposte:/data
    - /tmp/data/mail:/mail
    - /tmp/data/certs:/certs

smtp:
  build: postfix
  env_file: freeposte.env
  ports:
    - "25:25"
    - "465:465"
    - "587:587"
  links:
    - filter:lmtp
    - imap:sasl
  volumes:
    - /tmp/data/freeposte:/data
    - /tmp/data/logs:/logs
    - /tmp/data/certs:/certs

filter:
  build: amavis
  env_file: freeposte.env
  links:
    - imap:lmtp
  volumes:
    - /tmp/data/filter:/data

admin:
  build: admin
  env_file: freeposte.env
  volumes:
    - /tmp/data/freeposte:/data

webmail:
  build: roundcube
  env_file: freeposte.env
  links:
    - imap:imap
    - smtp:smtp
  volumes:
    - /tmp/data/webmail:/data
