defaultEntryPoints = ["http", "https"]
logLevel = "ERROR"
accessLogsFile = "/dev/stdout"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      MinVersion = "VersionTLS11"
      CipherSuites = ["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"]
    [[entryPoints.https.tls.certificates]]
    CertFile = "/certs/cert.pem"
    KeyFile = "/certs/key.pem"

[docker]
endpoint = "unix:///docker.sock"
domain = "{{ DOMAIN }}"
watch = true
exposedbydefault = false

