uwsgi:
  socket: /var/run/freeposte.sock
  chown-socket: www-data:www-data
  pidfile: /var/run/freeposte.pid
  master: true
  workers: 2

  uid: www-data
  gid: www-data

  vacuum: true
  plugins: python
  wsgi-file: /admin/run.py
  callable: app
  processes: 1
  pythonpath: /usr/lib/python2.7/site-packages
  pythonpath: /admin
  catch-exceptions: true
  post-buffering: 8192
